DROP DATABASE IF EXISTS playerDB;
CREATE DATABASE playerDB;
USE playerDB;

CREATE TABLE `scoreboard` (
  `id` INTEGER (11) AUTO_INCREMENT NOT NULL,
  `corrects` INTEGER (200) NOT NULL,
  `incorrects` INTEGER (200) NOT NULL,
 
 PRIMARY KEY (`id`)
);
